//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public long ID { get; set; }
        public Nullable<long> SubjectID { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
    }
}
