//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Capacty { get; set; }
        public string Notes { get; set; }
    }
}
